local root = assert(arg[1], "source root required")
local t = dofile("tests/testlib.lua")
local core = dofile(root .. "/usr/lib/sms2telegram/core.lua")

t.eq("UCS2 Chinese", assert(core.ucs2_to_utf8("77ED4FE1")), "短信")
t.eq("UCS2 phone", assert(core.ucs2_to_utf8("002B0038003600310033")), "+8613")
local value, err = core.ucs2_to_utf8("D800")
t.eq("reject surrogate", value, nil)
t.truthy("surrogate error", err and err:match("surrogate"))
t.eq("UTF-8 length", core.utf8_length("A短信🙂"), 4)
local head, tail = core.utf8_prefix("A短信🙂B", 3)
t.eq("UTF-8 prefix", head, "A短信")
t.eq("UTF-8 remainder", tail, "🙂B")

local function rejects_invalid_utf8(name, text)
  local ok = pcall(function() core.utf8_length(text) end)
  t.eq(name, tostring(ok), "false")
end
rejects_invalid_utf8("invalid continuation", string.char(0xC2, 0x41))
rejects_invalid_utf8("truncated sequence", string.char(0xE2, 0x82))
rejects_invalid_utf8("overlong encoding", string.char(0xE0, 0x80, 0x80))
rejects_invalid_utf8("encoded surrogate", string.char(0xED, 0xA0, 0x80))
rejects_invalid_utf8("codepoint above Unicode", string.char(0xF4, 0x90, 0x80, 0x80))
t.finish()
